const state = { screen: 'intro', evidence: new Set(), asked: 0, ending: null };
const stage = document.querySelector('#stage');
const progress = document.querySelector('#progress');
const shanPanel = document.querySelector('#shan-panel');
const shanLog = document.querySelector('#shan-log');
const askInput = document.querySelector('#ask-input');
const toast = document.querySelector('#toast');

const answers = [
  { test: /哪一年|年份|时间/, text: '你所在的起点是 1122 年，北宋末年。南宋要到 1127 年才建立。先记住这一点：你知道的是后世叙述，不是眼前人的亲身经验。' },
  { test: /文书|军队|去向/, text: '征发文书能证明“有人发出了命令”，不能单独证明军队最终抵达哪里。核对路线、天气和传递者，才知道一条消息能不能成为行动。' },
  { test: /岳飞|告诉|有用|召回/, text: '提前知道结局，不等于拥有改变结局的权力。你可以传递消息，但必须先回答：谁会相信你？谁能执行它？代价由谁承担？' },
  { test: /家书|百姓|普通人/, text: '家书不是军事证据，却能告诉你战争如何进入一个人的生活。别把“无关宏旨”误认为“没有价值”。' },
  { test: /路线|湿|天气|通行/, text: '湿损路线图说明道路正在变化。它不是一张答案图，而是一条提醒：信息的命运也受物理世界影响。' },
];

function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function setProgress(s){const map={intro:'01 / 05',awakening:'02 / 05',explore:'03 / 05',timeline:'04 / 05',choice:'05 / 05',end:'完成'};progress.textContent=map[s]||''}
function render(){setProgress(state.screen); if(state.screen==='intro') renderIntro(); if(state.screen==='awakening') renderAwakening(); if(state.screen==='explore') renderExplore(); if(state.screen==='timeline') renderTimeline(); if(state.screen==='choice') renderChoice(); if(state.screen==='end') renderEnd()}
function renderIntro(){stage.innerHTML=`<article class="card intro"><span class="eyebrow">知乎大千世界 · 文章小世界入口</span><h1>第一章<br>靖康前夜</h1><p>你只是想再看一个回答。屏幕上的问题却先问了你：<br>“如果已经知道结局，你会把答案交给谁？”</p><div class="hint">一章完整 Demo · 点击阅读与调查 · 预计 15 分钟</div><button class="cta" id="start">打开未读完的问题　→</button></article>`;document.querySelector('#start').onclick=()=>{state.screen='awakening';render()}}
function renderAwakening(){stage.innerHTML=`<article class="card scene"><div class="scene-title"><h2>纸上来客</h2><small>1122 年 · 北宋末年</small></div><p class="scene-copy">屋梁在视野里摇晃。你听见远处有人谈论年景、兵乱和迁徙。一个白色身影像印章一样落在纸面般的天空中。</p><div class="world" style="background:linear-gradient(180deg,#d9d5c5,#b2b8aa 60%,#6c7770 60%)"><div style="position:absolute;left:13%;bottom:18%;width:160px;height:120px;border-radius:50%;background:#303d3b2b"></div><div style="position:absolute;right:18%;top:18%;font-family:serif;color:#7f2928;font-size:34px;opacity:.8">看</div></div><div class="scene-actions"><span class="objective">系统提示：先问一个明确的问题。</span><button class="shan-btn" id="ask-first">向刘看山提问</button></div></article>`;document.querySelector('#ask-first').onclick=()=>{openShan();addMsg('user','这里是哪一年？');addMsg('ai',answers[0].text);state.asked++;setTimeout(()=>{state.screen='explore';render()},900)}}
function renderExplore(){const ready=state.evidence.has('letter')&&state.evidence.has('order')&&state.evidence.has('map');stage.innerHTML=`<article class="card scene"><div class="scene-title"><h2>驿路三证</h2><small>调查场景 · 线索 ${state.evidence.size} / 3</small></div><p class="scene-copy">时间快进到你能够自由行动的年纪。驿站、民居和渡口被一条湿冷的道路串在一起。三件物品正在等待你判断：它们能证明什么，又不能证明什么？</p><div class="world"><button class="object obj-letter" data-id="letter">未发出的家书</button><button class="object obj-order" data-id="order">征发文书</button><button class="object obj-map" data-id="map">湿损路线图</button><button class="object obj-soldier" id="soldier">军中同伴</button></div><div class="evidence">${state.evidence.has('letter')?'<span>家书 · 已核实</span>':''}${state.evidence.has('order')?'<span>文书 · 已核实</span>':''}${state.evidence.has('map')?'<span>路线图 · 已核实</span>':''}</div><div class="scene-actions"><span class="objective">${ready?'三件证据已收集。继续追问岳飞的命运。':'调查三件物品，并向人物核对至少一条线索。'}</span><div><button class="shan-btn" id="open-shan">问刘看山</button>${ready?'<button class="cta" id="continue" style="margin:0 0 0 8px;padding:10px 14px">继续　→</button>':''}</div></div></article>`;
document.querySelectorAll('.object[data-id]').forEach(btn=>btn.onclick=()=>inspect(btn.dataset.id));document.querySelector('#soldier').onclick=()=>{showToast('同伴低声说：消息要有人信，也要有路能走。');state.evidence.add('soldier');render()};document.querySelector('#open-shan').onclick=openShan;document.querySelector('#continue')?.addEventListener('click',()=>{state.screen='timeline';render()})}
function inspect(id){const data={letter:['letter','家书边缘被火燎黑，最后一行没有写完。它让你知道战争如何进入一个人的家。'],order:['order','文书盖着公印，写着征发与调动。它证明命令存在，却没有写出命令最终抵达哪里。'],map:['map','路线图被雨水打湿，渡口旁多了一道新的墨痕。天气和道路，正在改变消息的命运。']}[id];if(!state.evidence.has(id)){state.evidence.add(id);showToast(data[1]);render()}else showToast('你已经核对过这件线索。')}
function renderTimeline(){stage.innerHTML=`<article class="card scene"><div class="scene-title"><h2>二十年后的答案</h2><small>时间轴正在展开</small></div><p class="scene-copy">军中谈话里出现了一个名字：岳飞。你想起后世答案——1142 年，他会死。朱砂从纸缝里渗出，把 1122 年和 1142 年连成一道裂痕。</p><div class="world" style="background:linear-gradient(90deg,#e2d9c3 0 46%,#b2483b 46% 47%,#ded3bb 47% 100%);display:flex;align-items:center;justify-content:space-around;color:#3d4642;font-family:serif;font-size:25px"><span>1122<br><small style="font:12px sans-serif">你抵达</small></span><span style="color:#9f302c">⋯⋯</span><span>1142<br><small style="font:12px sans-serif">朱砂覆盖</small></span></div><div class="scene-actions"><span class="objective">再问一个问题，确认你真正知道的是什么。</span><button class="shan-btn" id="ask-timeline">向刘看山提问</button></div></article>`;document.querySelector('#ask-timeline').onclick=()=>{openShan();addMsg('user','我现在告诉岳飞有用吗？');addMsg('ai',answers[2].text);state.asked++;setTimeout(()=>{state.screen='choice';render()},1100)}}
function renderChoice(){stage.innerHTML=`<article class="card scene"><div class="scene-title"><h2>把答案交给谁</h2><small>关键选择 · 只剩一次传递机会</small></div><p class="scene-copy">你把三件证据放在桌面上。事实、背景和未知交叠在一起。现在，你可以把未来的消息交给传令者，也可以把普通人的证言封存下来。</p><div class="evidence"><span>已核实：${state.evidence.size} 条场景线索</span><span class="pending">仍存疑：消息是否会被相信</span></div><div class="choice-wrap"><button class="choice" data-ending="intervene"><strong>介入时间线</strong><small>把未来信息交给关键人物。你可能改变一个节点，也可能把未知的代价带给更多人。</small></button><button class="choice" data-ending="witness"><strong>保存证言</strong><small>不声称自己能改变大局，把你亲眼见到的过程留给未来的人阅读。</small></button></div></article>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{state.ending=b.dataset.ending;state.screen='end';render()})}
function renderEnd(){const altered=state.ending==='intervene';stage.innerHTML=`<article class="card end"><span class="stamp">时间线记录 · ${altered?'偏离':'见证'}</span><h2>${altered?'朱砂落下，答案先到了。':'灯火熄灭，证言留下来。'}</h2><p>${altered?'消息被送出，画卷上的一处结局发生偏移。可刘看山提醒你：改变一个节点，不会自动消除它背后的结构性矛盾。你第一次明白，答案抵达之后，问题才真正开始。':'你没有把后世的结论伪装成眼前人的命令。历史继续向前，但你把家书、文书和路线图放在了一起。未来有人读到它们时，会知道一个结局是怎样一步步发生的。'}</p><p class="quote">“知道结局，并不意味着理解过程。”<br><strong>只要有问题，就有回答。</strong></p><button class="cta" id="restart">再读一遍这个问题　↗</button></article>`;document.querySelector('#restart').onclick=()=>{state.screen='intro';state.evidence.clear();state.asked=0;state.ending=null;closeShan();render()}}
function openShan(){shanPanel.classList.remove('hidden');if(!shanLog.children.length)addMsg('ai','我是刘看山。问得越具体，答案越接近你眼前的世界。')}
function closeShan(){shanPanel.classList.add('hidden')}
function addMsg(type,text){const p=document.createElement('p');p.className='msg '+type;p.textContent=text;shanLog.appendChild(p);shanLog.scrollTop=shanLog.scrollHeight}
function ask(text){if(!text.trim())return;addMsg('user',text);const hit=answers.find(a=>a.test.test(text));addMsg('ai',hit?hit.text:'这个问题还没有落到眼前的证据上。先调查场景，再问我它能证明什么。');state.asked++;askInput.value=''}
document.querySelector('#close-shan').onclick=closeShan;document.querySelector('#ask-btn').onclick=()=>ask(askInput.value);askInput.addEventListener('keydown',e=>{if(e.key==='Enter')ask(askInput.value)});document.querySelectorAll('[data-ask]').forEach(b=>b.onclick=()=>ask(b.dataset.ask));
render();
